name: ci
on: [push, pull_request]
jobs:
    ci:
        runs-on: ubuntu-latest
        name: check and tests
        steps:
            - uses: actions/checkout@v2
            - uses: denolib/setup-deno@v2
              with:
                deno-version: v1.x
            - name: check format
              run: deno fmt --check
            - name: check linting
              run: deno lint --unstable
            - name: run tests
              run: deno test --allow-run
